# pull official base image
FROM python:3.10.1-slim-buster

# create directory for the app user
RUN mkdir -p /home/app

# create the app user
RUN addgroup --system app && adduser --system --group app

# create the appropriate directories
#ENV HOME=/home/app - this breaks poetry
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

# install system dependencies
RUN pip install -U pip \
    && apt-get update \
    && apt-get -y install netcat gcc curl postgresql \
    && apt-get clean \
    && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
ENV PATH="${PATH}:/root/.poetry/bin"

# install python dependencies
WORKDIR /usr/src/app
COPY ./poetry.lock ./pyproject.toml $APP_HOME

# install python dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi \
    && poetry add "uvicorn[standard]==0.16.0"

# add app
COPY . .

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

# run gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker
